
  - alias: 'Kitchen Night Lights On'
    trigger: 
      platform: sun
      event: sunset
      offset: '-00:30:00'
    action:
      service: light.turn_on
      entity_id: group.KitchenNightLights 
  - alias: 'Kitchen Night Lights Off'
    trigger: 
      platform: sun
      event: sunrise
      offset: '+00:30:00'
    action:
      service: light.turn_off
      entity_id: group.KitchenNightLights
