homeassistant:
  name: Wier Home
  latitude: 41.7139
  longitude: -85.7455
  elevation: 265
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: 192.168.2.20
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

sensor: !include sensor.yaml
light: !include light.yaml 
automation: !include automation.yaml
group: !include group.yaml
camera: !include camera.yaml
